name: ebmusica
favicon: null
layout_spectrum: 0.6772334228735417
typography_spectrum: 0.2398589770309627
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.9965235774870962
  rhythmicContrast: 0.5
purpose: []
